language: rust
cache: cargo

install:
  - rustc -vV
  - cargo -vV

jobs:
  allow_failures:
    - rust: nightly
      stage: foo
    - rust: nightly
      stage: bar

  include:
    - name: foo
      stage: foo
      rust: nightly
      cache: false
      script: exit 1

    - name: bar
      stage: bar
      rust: nightly
      cache: false
      script: exit 1

    - name: baz
      stage: baz
      rust: nightly
      cache: false
      script: exit 1
